version: '3.7'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_DATABASE=vm
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - php
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - php
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: vm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres-data:
