apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laravel-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: laravel-app
  endpoints:
  - port: http
    path: /metrics
