name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP and Node.js (if applicable)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or your preferred version

      # Step 3: Install dependencies
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node.js dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: |
          vendor/bin/phpunit  # Adjust to your test command
          npm test  # Adjust to your test command

      # Step 5: Build Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vm:latest  # Change to your image name

      # Step 6: Set up Kubernetes context
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Step 7: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/laravel-deployment.yaml
          kubectl apply -f k8s/laravel-service.yaml
          kubectl apply -f k8s/nginx_configMap.yaml
          kubectl apply -f k8s/nginx_deployment.yaml
          kubectl apply -f k8s/nginx_ervice.yaml

