name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout code
        uses: actions/checkout@v2

   
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

     
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node.js dependencies
        run: npm install

      
      - name: Run tests
        run: |
          php artisan test  

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vm:latest

      
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/laravel-deployment.yaml
          kubectl apply -f k8s/laravel-service.yaml
          kubectl apply -f k8s/nginx_configMap.yaml
          kubectl apply -f k8s/nginx_deployment.yaml
          kubectl apply -f k8s/nginx_ervice.yaml

